name: abushakir
version: 0.1.4
homepage: https://github.com/Nabute/Abushakir
description: A Dart/ Flutter Package for Ethiopian calendar system (ባሕረ ሃሳብ). It can help you integrate Ethiopian DateTime, calendar and all the movable fastings with respective holidays.
environment: 
  sdk: '>=2.2.2 <3.0.0'
dependencies: 
  equatable: ^1.1.0
dev_dependencies: 
  test: ^1.14.2
