name: abushakir
description: A Dart Package for Ethiopian Calendar (ባሕረ ሃሳብ).
version: 0.0.1
author: Nabute Nigusse nabute925@gmail.com; Nahom 4nahom@gmail.com
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  equatable: ^1.1.0

dev_dependencies:
  test: ^1.14.2